# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='hiveenvelope',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65nvelope.proto\x12\x0chiveenvelope\"[\n\x13HiveEnvelopeMessage\x12\x0e\n\x06target\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0c\n\x04\x66rom\x18\x05 \x01(\x05\x62\x06proto3')
)




_HIVEENVELOPEMESSAGE = _descriptor.Descriptor(
  name='HiveEnvelopeMessage',
  full_name='hiveenvelope.HiveEnvelopeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='hiveenvelope.HiveEnvelopeMessage.target', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='hiveenvelope.HiveEnvelopeMessage.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='hiveenvelope.HiveEnvelopeMessage.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='hiveenvelope.HiveEnvelopeMessage.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='hiveenvelope.HiveEnvelopeMessage.from', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['HiveEnvelopeMessage'] = _HIVEENVELOPEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HiveEnvelopeMessage = _reflection.GeneratedProtocolMessageType('HiveEnvelopeMessage', (_message.Message,), dict(
  DESCRIPTOR = _HIVEENVELOPEMESSAGE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:hiveenvelope.HiveEnvelopeMessage)
  ))
_sym_db.RegisterMessage(HiveEnvelopeMessage)


# @@protoc_insertion_point(module_scope)
